image: sopra.informatik.uni-stuttgart.de:5050/kib3-student-projects/kib3-stupro-ss-22:latest

stages:
  - lint
  - test
  - zip-plugin

variables:
  DB: "mariadb"
  MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
  TRAVIS_BUILD_DIR: "$CI_PROJECT_DIR"
  MOODLE_BRANCH: "MOODLE_311_STABLE"
  MOODLE_DIR: "/var/www/html/moodle"
  MOODLE_BEHAT_WDHOST: "http://selenium-standalone-chrome:4444/wd/hub"
  MOODLE_START_BEHAT_SERVERS: "NO"
  IGNORE_NAMES: "lib.php, upgrade.php"

.install_moodle:
  rules:
    - changes:
        - "*.md"
        - "setup/*"
      when: never
    - when: always
  before_script:
    - export PATH="/var/www/html/ci/bin:/var/www/html/ci/vendor/bin:$PATH"
    - moodle-plugin-ci install --moodle=$MOODLE_DIR --db-host=mariadb --no-init --plugin=$CI_PROJECT_DIR -vvv
    - cd $MOODLE_DIR
    - export IPADDRESS=`grep "$HOSTNAME$" /etc/hosts | awk '{print $1}'`
    - php -S $IPADDRESS:8000 -t $MOODLE_DIR > /dev/null 2>&1 &

lint:
  stage: lint
  rules:
    - changes:
        - "*.md"
        - "setup/*"
        - ".vscode/*"
      when: never
    - when: always
  script:
    - export PATH="/var/www/html/ci/bin:/var/www/html/ci/vendor/bin:$PATH"
    # these checks can be run without the Moodle install:
    - moodle-plugin-ci phplint $CI_PROJECT_DIR
    - moodle-plugin-ci phpcpd $CI_PROJECT_DIR
    - moodle-plugin-ci savepoints $CI_PROJECT_DIR

test:
  stage: test
  rules:
    - changes:
        - "*.md"
        - "setup/*"
        - ".vscode/*"
      when: never
    - when: always
  extends: .install_moodle
  services:
    - mariadb:10.7.4
  script:
    - moodle-plugin-ci phpmd
    - moodle-plugin-ci validate
    - moodle-plugin-ci phpunit
    - moodle-plugin-ci codechecker --max-warnings 0
    - moodle-plugin-ci grunt
    - moodle-plugin-ci phpdoc

zip-plugin:
  stage: zip-plugin
  script:
    - composer install
  artifacts:
    # Name of the resulting .zip
    name: moodle-mod_jupyter
    paths:
      - ./*
  only:
    refs:
      # Run only on specific branch
      - main
